# Generated by Django 3.1.6 on 2021-02-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=40)),
                ('tweets', models.ManyToManyField(to='thing.Tweet')),
            ],
        ),
    ]
