# Generated by Django 3.1.6 on 2021-02-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0003_auto_20210202_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='short_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='slack_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
